<<<<<<< Updated upstream
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 2.2.5 on 2020-10-13 02:52
=======
# Generated by Django 2.2.5 on 2020-10-12 15:38
>>>>>>> sanbai
=======
# Generated by Django 2.2.5 on 2020-10-13 02:50
>>>>>>> mingge
=======
# Generated by Django 2.2.5 on 2020-10-13 02:02
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< Updated upstream
<<<<<<< HEAD
        ('gathering', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gathering', '0001_initial'),
>>>>>>> mingge
=======
        ('gathering', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='users',
            field=models.ManyToManyField(related_name='gathers', to=settings.AUTH_USER_MODEL, verbose_name='参加者'),
        ),
    ]
