# Generated by Django 2.2.5 on 2020-10-13 02:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('publishtime', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('userid', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('visits', models.IntegerField(default=0)),
                ('thumbup', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
                ('avatar', models.CharField(max_length=255)),
                ('collected', models.BooleanField(default=False)),
                ('hasthumbup', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spit.Spit')),
            ],
        ),
    ]
